// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz7AKNpfNNRQPhhl-hF48-G3HUikjF14Q',
    appId: '1:868142073986:web:184822badc6473da414c9b',
    messagingSenderId: '868142073986',
    projectId: 'flutter-instagram-clone-227f8',
    authDomain: 'flutter-instagram-clone-227f8.firebaseapp.com',
    storageBucket: 'flutter-instagram-clone-227f8.appspot.com',
    measurementId: 'G-6S591ZVQ5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3UDWCxGoTk9MlFijo4efD22MkyPARK7c',
    appId: '1:868142073986:android:bcfd094e6e8bf116414c9b',
    messagingSenderId: '868142073986',
    projectId: 'flutter-instagram-clone-227f8',
    storageBucket: 'flutter-instagram-clone-227f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArlKHUwsDi8s1nElwu07jW9F_6fgu7qTM',
    appId: '1:868142073986:ios:4e3645fff2a6df27414c9b',
    messagingSenderId: '868142073986',
    projectId: 'flutter-instagram-clone-227f8',
    storageBucket: 'flutter-instagram-clone-227f8.appspot.com',
    iosBundleId: 'com.example.flutterInstagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArlKHUwsDi8s1nElwu07jW9F_6fgu7qTM',
    appId: '1:868142073986:ios:f2d6ea1c2cd5b915414c9b',
    messagingSenderId: '868142073986',
    projectId: 'flutter-instagram-clone-227f8',
    storageBucket: 'flutter-instagram-clone-227f8.appspot.com',
    iosBundleId: 'com.example.flutterInstagramClone.RunnerTests',
  );
}
